#!/usr/bin/env python3
"""Generate SLURM launchers for all full optimization runs."""

from pathlib import Path


PROJECT_DIR = "/home/hpc/users/ml_models/rebeka.maneva/nlp"
RUN_DIR = Path(PROJECT_DIR) / "optimizations" / "full_runs"

ALGORITHMS = ("rs", "ts", "bayes", "ga", "hc", "sa")
WINDOWS = (100, 200, 500)

MODELS = {
    "hyena": {
        "job_prefix": "hyena",
        "python": "/home/hpc/users/ml_models/rebeka.maneva/venv_hyenadna/bin/python",
        "script": "${OPT_DIR}/optimize_hf_seqclf.py",
        "model_name": "LongSafari/hyenadna-tiny-16k-seqlen-d128-hf",
        "output_prefix": "opt_hyena",
        "mode": "hf",
    },
    "nt": {
        "job_prefix": "nt",
        "python": "/home/hpc/users/ml_models/rebeka.maneva/venv_nt/bin/python",
        "script": "${OPT_DIR}/optimize_hf_seqclf.py",
        "model_name": "InstaDeepAI/nucleotide-transformer-v2-100m-multi-species",
        "output_prefix": "opt_nt",
        "mode": "hf",
    },
    "dnabert2": {
        "job_prefix": "dnabert2",
        "python": "/home/hpc/users/ml_models/rebeka.maneva/venv_dnabert2/bin/python",
        "script": "${OPT_DIR}/optimize_dnabert2.py",
        "model_name": "zhihan1996/DNABERT-2-117M",
        "output_prefix": "opt_dnabert2",
        "mode": "dnabert2",
    },
}


def header(
    job_name: str,
    log_name: str,
    fp16_default: str = "0",
    gradient_checkpointing_default: str = "0",
) -> str:
    return f"""#!/bin/bash
# Auto-generated by optimizations/generate_full_run_scripts.py
# Full optimization launcher for one model, algorithm, and window size.

#SBATCH --job-name={job_name}
#SBATCH --partition=openlab-queue
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=48G
#SBATCH --time=48:00:00
#SBATCH --output={PROJECT_DIR}/logs/full_opt/{log_name}_%j.out
#SBATCH --error={PROJECT_DIR}/logs/full_opt/{log_name}_%j.err

set -euo pipefail
set -x

PROJECT_DIR={PROJECT_DIR}
OPT_DIR=${{PROJECT_DIR}}/optimizations
LOG_DIR=${{PROJECT_DIR}}/logs/full_opt

HF_HOME=/home/hpc/users/ml_models/rebeka.maneva/.cache/huggingface
TRITON_HOME=/home/hpc/users/ml_models/rebeka.maneva/.triton
TRITON_CACHE_DIR=${{TRITON_HOME}}/cache
TORCHINDUCTOR_CACHE_DIR=/home/hpc/users/ml_models/rebeka.maneva/.torchinductor

N_TRIALS=${{N_TRIALS:-30}}
SEARCH_EPOCHS=${{SEARCH_EPOCHS:-5}}
FULL_EPOCHS=${{FULL_EPOCHS:-50}}
SEED=${{SEED:-42}}
MAX_LENGTH=${{MAX_LENGTH:-512}}
FP16=${{FP16:-{fp16_default}}}
BF16=${{BF16:-0}}
GRADIENT_CHECKPOINTING=${{GRADIENT_CHECKPOINTING:-{gradient_checkpointing_default}}}

mkdir -p "${{LOG_DIR}}" "${{TRITON_HOME}}" "${{TRITON_CACHE_DIR}}" "${{TORCHINDUCTOR_CACHE_DIR}}"
"""


def env_block(python_path: str) -> str:
    return f"""
PYTHON={python_path}

if [ ! -x "${{PYTHON}}" ]; then
    echo "ERROR: interpreter not found or not executable: ${{PYTHON}}"
    exit 1
fi
"""


def env_i_prefix() -> str:
    return """env -i \\
    PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \\
    HOME="${HOME}" \\
    HF_HOME="${HF_HOME}" \\
    TRANSFORMERS_CACHE="${HF_HOME}/transformers" \\
    TOKENIZERS_PARALLELISM="false" \\
    TORCHDYNAMO_DISABLE="1" \\
    CUDA_LAUNCH_BLOCKING="1" \\
    FLASH_ATTENTION_DO_NOT_USE_TRITON="1" \\
    TRITON_HOME="${TRITON_HOME}" \\
    TRITON_CACHE_DIR="${TRITON_CACHE_DIR}" \\
    TORCHINDUCTOR_CACHE_DIR="${TORCHINDUCTOR_CACHE_DIR}" \\
    CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" \\
    "${PYTHON}" """


def hf_script(model_key: str, cfg: dict, algo: str, window: int) -> str:
    job_name = f"opt_{model_key}_{algo}_{window}bp"
    out_dir = f"${{PROJECT_DIR}}/outputs/{cfg['output_prefix']}_{window}bp/{algo}"
    data_csv = f"${{PROJECT_DIR}}/data/promoter_binary_{window}bp.csv"
    fp16_default = "1" if model_key == "hyena" else "0"
    gc_default = "1" if model_key == "hyena" else "0"
    return (
        header(job_name, job_name, fp16_default, gc_default)
        + env_block(cfg["python"])
        + f"""
DATA_CSV={data_csv}
OUT_DIR={out_dir}
mkdir -p "${{OUT_DIR}}"

EXTRA_ARGS=()
if [ "${{FP16}}" = "1" ]; then EXTRA_ARGS+=(--fp16); fi
if [ "${{BF16}}" = "1" ]; then EXTRA_ARGS+=(--bf16); fi
if [ "${{GRADIENT_CHECKPOINTING}}" = "1" ]; then EXTRA_ARGS+=(--gradient-checkpointing); fi

echo "Starting {model_key} {window}bp {algo} full optimization - $(date)"
echo "GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo 'N/A')"
echo "Output: ${{OUT_DIR}}"

"""
        + env_i_prefix()
        + f"""${{OPT_DIR}}/optimize_hf_seqclf.py \\
    --train-csv "${{DATA_CSV}}" \\
    --split-from-single-csv \\
    --model-name "{cfg['model_name']}" \\
    --output-dir "${{OUT_DIR}}" \\
    --algorithm "{algo}" \\
    --n-trials "${{N_TRIALS}}" \\
    --search-epochs "${{SEARCH_EPOCHS}}" \\
    --full-epochs "${{FULL_EPOCHS}}" \\
    --max-length "${{MAX_LENGTH}}" \\
    --seed "${{SEED}}" \\
    --trust-remote-code \\
    --study-name "{model_key}_{window}bp_{algo}" \\
    --storage "sqlite:///${{OUT_DIR}}/study.db" \\
    "${{EXTRA_ARGS[@]}}"

echo "Finished {model_key} {window}bp {algo} full optimization - $(date)"
"""
    )


def dnabert2_script(cfg: dict, algo: str, window: int) -> str:
    job_name = f"opt_dnabert2_{algo}_{window}bp"
    out_dir = f"${{PROJECT_DIR}}/outputs/{cfg['output_prefix']}_{window}bp/{algo}"
    data_dir = f"${{PROJECT_DIR}}/data/dnabert2_{window}"
    return (
        header(job_name, job_name)
        + env_block(cfg["python"])
        + f"""
DATA_DIR={data_dir}
OUT_DIR={out_dir}
mkdir -p "${{OUT_DIR}}"

EXTRA_ARGS=()
if [ "${{FP16}}" = "1" ]; then EXTRA_ARGS+=(--fp16); fi

echo "Starting dnabert2 {window}bp {algo} full optimization - $(date)"
echo "GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo 'N/A')"
echo "Output: ${{OUT_DIR}}"

"""
        + env_i_prefix()
        + f"""${{OPT_DIR}}/optimize_dnabert2.py \\
    --data-path "${{DATA_DIR}}" \\
    --model-name "{cfg['model_name']}" \\
    --output-dir "${{OUT_DIR}}" \\
    --algorithm "{algo}" \\
    --n-trials "${{N_TRIALS}}" \\
    --search-epochs "${{SEARCH_EPOCHS}}" \\
    --full-epochs "${{FULL_EPOCHS}}" \\
    --max-length "${{MAX_LENGTH}}" \\
    --seed "${{SEED}}" \\
    --study-name "dnabert2_{window}bp_{algo}" \\
    --storage "sqlite:///${{OUT_DIR}}/study.db" \\
    "${{EXTRA_ARGS[@]}}"

echo "Finished dnabert2 {window}bp {algo} full optimization - $(date)"
"""
    )


def submitter(script_names: list[str]) -> str:
    names = " ".join(script_names)
    return f"""#!/bin/bash
# Submit all generated full optimization jobs.
# Dry run: DRY_RUN=1 bash optimizations/full_runs/submit_all_full_optimizations.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
DRY_RUN="${{DRY_RUN:-0}}"

SCRIPTS=(
{chr(10).join(f'    "{name}"' for name in script_names)}
)

count=0
for script in "${{SCRIPTS[@]}}"; do
    cmd=(sbatch "${{SCRIPT_DIR}}/${{script}}")
    if [ "${{DRY_RUN}}" = "1" ]; then
        echo "[DRY RUN] ${{cmd[*]}}"
    else
        "${{cmd[@]}}"
    fi
    count=$((count + 1))
done

echo "Total jobs: ${{count}}"
"""


def main() -> None:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    script_names: list[str] = []

    for model_key, cfg in MODELS.items():
        for window in WINDOWS:
            for algo in ALGORITHMS:
                script_name = f"run_{model_key}_{algo}_{window}bp.sh"
                path = RUN_DIR / script_name
                if cfg["mode"] == "hf":
                    text = hf_script(model_key, cfg, algo, window)
                else:
                    text = dnabert2_script(cfg, algo, window)
                path.write_text(text)
                path.chmod(0o755)
                script_names.append(script_name)

    submit_path = RUN_DIR / "submit_all_full_optimizations.sh"
    submit_path.write_text(submitter(script_names))
    submit_path.chmod(0o755)
    print(f"Generated {len(script_names)} launchers in {RUN_DIR}")


if __name__ == "__main__":
    main()
